[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
sdl2 = { version = "0.36", features = ["ttf", "image"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
